name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t devops-app:test .

      - name: Validate Docker Compose
        run: docker compose config

      - name: Deploy to Droplet
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e

            echo "Connected to Droplet"

            cd /home/mitziel/node-postgres-app

            echo "Before deploy:"
            git rev-parse --short HEAD

            git fetch origin main
            git reset --hard origin/main

            echo "After pull:"
            git rev-parse --short HEAD

            docker compose up -d --build

            docker compose ps

            curl --fail http://127.0.0.1:8083